package filter

// apiNotCompared contains API paths that are skipped by default (when no explicit filters are set).
var apiNotCompared = []string{
	"mainnet/engine_getClientVersionV1",
	"mainnet/trace_rawTransaction",
	"mainnet/engine_",
}

// testsOnLatest contains tests that operate on the latest block.
// These are only run when the -L flag is set.
var testsOnLatest = []string{
	"mainnet/debug_traceBlockByNumber/test_24.json",
	"mainnet/debug_traceBlockByNumber/test_30.json",
	"mainnet/debug_traceCall/test_22.json",
	"mainnet/debug_traceCall/test_33.json",
	"mainnet/debug_traceCall/test_34.json",
	"mainnet/debug_traceCall/test_35.json",
	"mainnet/debug_traceCall/test_36.json",
	"mainnet/debug_traceCall/test_37.json",
	"mainnet/debug_traceCall/test_38.json",
	"mainnet/debug_traceCall/test_39.json",
	"mainnet/debug_traceCall/test_40.json",
	"mainnet/debug_traceCall/test_41.json",
	"mainnet/debug_traceCall/test_42.json",
	"mainnet/debug_traceCall/test_43.json",
	"mainnet/debug_traceCallMany/test_11.json",
	"mainnet/debug_traceCallMany/test_12.json",
	"mainnet/eth_blobBaseFee",
	"mainnet/eth_blockNumber",
	"mainnet/eth_call/test_20.json",
	"mainnet/eth_call/test_28.json",
	"mainnet/eth_call/test_29.json",
	"mainnet/eth_call/test_36.json",
	"mainnet/eth_call/test_37.json",
	"mainnet/eth_callBundle/test_09.json",
	"mainnet/eth_createAccessList/test_18.json",
	"mainnet/eth_createAccessList/test_19.json",
	"mainnet/eth_createAccessList/test_20.json",
	"mainnet/eth_createAccessList/test_22.json",
	"mainnet/eth_estimateGas/test_01",
	"mainnet/eth_estimateGas/test_02",
	"mainnet/eth_estimateGas/test_03",
	"mainnet/eth_estimateGas/test_04",
	"mainnet/eth_estimateGas/test_05",
	"mainnet/eth_estimateGas/test_06",
	"mainnet/eth_estimateGas/test_07",
	"mainnet/eth_estimateGas/test_08",
	"mainnet/eth_estimateGas/test_09",
	"mainnet/eth_estimateGas/test_10",
	"mainnet/eth_estimateGas/test_11",
	"mainnet/eth_estimateGas/test_12",
	"mainnet/eth_estimateGas/test_21",
	"mainnet/eth_estimateGas/test_22",
	"mainnet/eth_estimateGas/test_23",
	"mainnet/eth_estimateGas/test_27",
	"mainnet/eth_feeHistory/test_07.json",
	"mainnet/eth_feeHistory/test_22.json",
	"mainnet/eth_gasPrice",
	"mainnet/eth_getBalance/test_03.json",
	"mainnet/eth_getBalance/test_26.json",
	"mainnet/eth_getBalance/test_27.json",
	"mainnet/eth_getBlockTransactionCountByNumber/test_03.json",
	"mainnet/eth_getBlockByNumber/test_10.json",
	"mainnet/eth_getBlockByNumber/test_27.json",
	"mainnet/eth_getBlockReceipts/test_07.json",
	"mainnet/eth_getCode/test_05.json",
	"mainnet/eth_getCode/test_06.json",
	"mainnet/eth_getCode/test_07.json",
	"mainnet/eth_getLogs/test_21.json",
	"mainnet/eth_getProof/test_01.json",
	"mainnet/eth_getProof/test_02.json",
	"mainnet/eth_getProof/test_03.json",
	"mainnet/eth_getProof/test_04.json",
	"mainnet/eth_getProof/test_05.json",
	"mainnet/eth_getProof/test_06.json",
	"mainnet/eth_getProof/test_07.json",
	"mainnet/eth_getProof/test_08.json",
	"mainnet/eth_getProof/test_09.json",
	"mainnet/eth_getProof/test_10.json",
	"mainnet/eth_getProof/test_11.json",
	"mainnet/eth_getProof/test_12.json",
	"mainnet/eth_getProof/test_13.json",
	"mainnet/eth_getProof/test_14.json",
	"mainnet/eth_getProof/test_15.json",
	"mainnet/eth_getProof/test_16.json",
	"mainnet/eth_getProof/test_17.json",
	"mainnet/eth_getProof/test_18.json",
	"mainnet/eth_getProof/test_19.json",
	"mainnet/eth_getProof/test_20.json",
	"mainnet/eth_getRawTransactionByBlockNumberAndIndex/test_11.json",
	"mainnet/eth_getRawTransactionByBlockNumberAndIndex/test_12.json",
	"mainnet/eth_getRawTransactionByBlockNumberAndIndex/test_13.json",
	"mainnet/eth_getStorageAt/test_04.json",
	"mainnet/eth_getStorageAt/test_07.json",
	"mainnet/eth_getStorageAt/test_08.json",
	"mainnet/eth_getTransactionByBlockNumberAndIndex/test_02.json",
	"mainnet/eth_getTransactionByBlockNumberAndIndex/test_08.json",
	"mainnet/eth_getTransactionByBlockNumberAndIndex/test_09.json",
	"mainnet/eth_getTransactionCount/test_02.json",
	"mainnet/eth_getTransactionCount/test_07.json",
	"mainnet/eth_getTransactionCount/test_08.json",
	"mainnet/eth_getUncleCountByBlockNumber/test_03.json",
	"mainnet/eth_getUncleByBlockNumberAndIndex/test_02.json",
	"mainnet/eth_maxPriorityFeePerGas",
	"mainnet/eth_simulateV1/test_04.json",
	"mainnet/eth_simulateV1/test_05.json",
	"mainnet/eth_simulateV1/test_06.json",
	"mainnet/eth_simulateV1/test_07.json",
	"mainnet/eth_simulateV1/test_12.json",
	"mainnet/eth_simulateV1/test_13.json",
	"mainnet/eth_simulateV1/test_14.json",
	"mainnet/eth_simulateV1/test_15.json",
	"mainnet/eth_simulateV1/test_16.json",
	"mainnet/eth_simulateV1/test_25.json",
	"mainnet/eth_simulateV1/test_27.json",
	"mainnet/erigon_blockNumber/test_4.json",
	"mainnet/erigon_blockNumber/test_6.json",
	"mainnet/ots_hasCode/test_10.json",
	"mainnet/ots_searchTransactionsBefore/test_02.json",
	"mainnet/parity_listStorageKeys",
	"mainnet/trace_block/test_25.json",
	"mainnet/trace_call/test_26.json",
	"mainnet/trace_call/test_27.json",
	"mainnet/trace_call/test_28.json",
	"mainnet/trace_call/test_29.json",
	"mainnet/trace_callMany/test_15.json",
	"mainnet/trace_filter/test_25.json",
	"mainnet/trace_replayBlockTransactions/test_36.json",
}

// testsNotComparedMessage contains tests where the "message" field is not compared.
var testsNotComparedMessage = []string{}

// testsNotComparedError contains tests where the "error" field is not compared.
var testsNotComparedError = []string{}
